### PR TITLE
Add ADR Process Description

### PR DESCRIPTION
**Pull request by justinborromeo**

### CODE REVIEW

**Comment by AbhiPrasad** [comment]
@LeozMaxwellJilliams @ELozhkin @GodGreg @petorsong 

Please read over and give your thoughts!

**Review by AbhiPrasad — APPROVED** [review]
nit: formatting looks a little wack ngl

still sick though 🚀

**Review by gregmaxin — APPROVED** [review]

**Comment by LeozMaxwellJilliams** [comment]
LGTM, should we add a potential timeline of when this should be done by since "after scoping is complete" might be a bit vague. This might help give PLs and PMs on new projects a better sense of what to do in the first couple weeks.

**Comment by justinborromeo** [comment]
@LeozMaxwellJilliams I'll edit it to say "immediately after scoping is complete".  I'm hesitant in adding a hard timeline for completing this document after scoping because it really depends on the design doc's level of detail and the team's design process.

**Pull request merged**
